### ISSUE TITLE
Qual deverá ser a forma de governo do futuro?

### ISSUE THREAD

**Issue by Miguel0Almeida** [Redot-Engine/redot-engine#101]
### Tested versions

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/bae2e72d-b9b9-48c2-b8a2-b3b3e2b092c7)

cowards

![Captura de tela de 2024-10-02 15-05-47](https://github.com/user-attachments/assets/4b7dd65e-f769-4e71-a2dd-a6fab7cf70b5)

Free Speech you do review bombing on Godot I call you what you are COWARDS

### System information

Alguns de nossos leitores mais jovens respondem: ‘Como você pode perguntar isto? Você é republicano’"

### Issue description

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/bae2e72d-b9b9-48c2-b8a2-b3b3e2b092c7)

cowards

![Captura de tela de 2024-10-02 15-05-47](https://github.com/user-attachments/assets/4b7dd65e-f769-4e71-a2dd-a6fab7cf70b5)

Free Speech you do review bombing on Godot I call you what you are COWARDS

### Steps to reproduce

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/bae2e72d-b9b9-48c2-b8a2-b3b3e2b092c7)

cowards

![Captura de tela de 2024-10-02 15-05-47](https://github.com/user-attachments/assets/4b7dd65e-f769-4e71-a2dd-a6fab7cf70b5)

Free Speech you do review bombing on Godot I call you what you are COWARDS

### Minimal reproduction project (MRP)

You creator is a Transphobe this is why this fork exists ADIMIT IT AND BE A MAN DREW MAKE IT CLEAR.

![cowards](https://github.com/user-attachments/assets/bae2e72d-b9b9-48c2-b8a2-b3b3e2b092c7)

cowards

![Captura de tela de 2024-10-02 15-05-47](https://github.com/user-attachments/assets/4b7dd65e-f769-4e71-a2dd-a6fab7cf70b5)

Free Speech you do review bombing on Godot I call you what you are COWARDS

**Comment by CristianoBarone** [comment]
We get that the repository maintainer did this and that, but we LITERALLY only care about the engine and Godot has been unresponsive to our requests. Not only that but they've been bashing against us recently, even to those like me who were not involved in the Twitter drama (which by the way, it's a very sad thing to happen, they literally pay more attention on tweeting shit than to fix their mess of an engine). I believe Godot has followed the same path Unity has, and so I look forward to a much more actually open project, which is Redot, because as a developer I feel an engine should care about me instead of caring about politics (whichever their views may be, I have no problem with an engine made by people that endorse an agenda, as long as they don't bleed that content in the engine and ignore my requests making my job harder because they're not doing theirs). Redot doesn't cite politics into its mission, and that's why we chose it, doesn't matter if its maintainer endorses LGBTQ+ agendas or not, the creator of Godot has been vocal about it for years on HIS OWN PROFILE and no one has had a problem with that, the problem is that instead of adding support for standard formats and adhering to standard game development practices as one would expect them to do they're ranting about unrelated topics on Twitter making our job as developers utter shit.

**Comment by repomansez** [comment]
@CristianoBarone no point arguing with these brainlets, let them rot in their own stupidity

**Comment by MaxyBlack** [comment]
> We get that the repository maintainer did this and that, but we LITERALLY only care about the engine and Godot has been unresponsive to our requests. Not only that but they've been bashing against us recently, even to those like me who were not involved in the Twitter drama (which by the way, it's a very sad thing to happen, they literally pay more attention on tweeting shit than to fix their mess of an engine). I believe Godot has followed the same path Unity has, and so I look forward to a much more actually open project, which is Redot, because as a developer I feel an engine should care about me instead of caring about politics (whichever their views may be, I have no problem with an engine made by people that endorse an agenda, as long as they don't bleed that content in the engine and ignore my requests making my job harder because they're not doing theirs). Redot doesn't cite politics into its mission, and that's why we chose it, doesn't matter if its maintainer endorses LGBTQ+ agendas or not, the creator of Godot has been vocal about it for years on HIS OWN PROFILE and no one has had a problem with that, the problem is that instead of adding support for standard formats and adhering to standard game development practices as one would expect them to do they're ranting about unrelated topics on Twitter making our job as developers utter shit.

do not interact, go to profile, click report, report for spam, and link this ticket.

**Comment by FireBrandMint** [comment]
> do not interact, go to profile, click report, report for spam, and link this ticket.

As a brazilian, this is shameful. I wish github staff would act faster.

**Comment by Miguel0Almeida** [comment]
> @CristianoBarone no point arguing with these brainlets, let them rot in their own stupidity

![Screenshot 2024-10-02 at 15-50-01 Miguel Gomes de Almeida-1 pdf](https://github.com/user-attachments/assets/97ba2177-5e8c-4740-a11b-f526b10e6e9f)
eu na verdade sou um GENIO ❤️

**Comment by Miguel0Almeida** [comment]
> @CristianoBarone no point arguing with these brainlets, let them rot in their own stupidity

![Screenshot 2024-10-02 at 15-52-03 Miguel Gomes de Almeida-1 pdf](https://github.com/user-attachments/assets/1ffd1604-6df6-4dfd-ac19-6cb1679280dd)
na real eu sou um GENIO ❤️
